### PR TITLE
Added czech translations.

### PR DESCRIPTION
**Pull request by mat-hew1**
Czech translations added into all .js service files.

### CODE REVIEW

**Comment by richard67** [comment]
List of available languages in description of data-Lang parameter in Readme.md and Readme_de.md has to be changed, too.

**Comment by mat-hew1** [comment]
Thanks for the hint. Is done.

**Comment by richard67** [comment]
@compeak I think the `needs documentation` label can be removed now.

**Comment by compeak** [comment]
Thanks.

**Pull request merged**
