### PR TITLE
Add VK and Telegram services

### PR DESCRIPTION
**Pull request by dennis95stumm**
Added telegram and vk services.

Related issues: #238 and #147

### CODE REVIEW

**Comment by compeak** [comment]
Thank you.

**Comment by richard67** [comment]
@dennis95stumm Is there any reason why you have chosen to use `popup: false` in telegram.js and not `popup: true`?

**Comment by dennis95stumm** [comment]
No.

**Comment by richard67** [comment]
@dennis95stumm @compeak Well, it should be corrected to popup=true. Shall I make a PR tonight for that?

**Comment by dennis95stumm** [comment]
@richard67 Yes. It would be nice :+1:.

**Comment by compeak** [comment]
I fixed it in 1555a72.

**Comment by richard67** [comment]
@dennis95stumm @compeak Meanwhile I have made a PR for the PHP backend to add VK, see [https://github.com/heiseonline/shariff-backend-php/pull/130](https://github.com/heiseonline/shariff-backend-php/pull/130), so of that will be accepted, we will soon be able to see share counters for VK in Shariff when using the PHP backend.

**Pull request merged**
