### PR TITLE
Add MediaWiki extension to both Readme files

### PR DESCRIPTION
**Pull request by stefahn**

### CODE REVIEW

**Comment by stefahn** [comment]
Do I have to ping someone so that this becomes visible? I'm relatively new to Git(hub). 
@compeak  :)

**Comment by compeak** [comment]
> Do I have to ping someone so that this becomes visible?

No. I'm currently the sole maintainer, so things can take some time.

**Comment by compeak** [comment]
Thanks.

**Comment by stefahn** [comment]
Thanks for your work and the merge :)

When I do " git push origin my_branch_name" on my shell, do I create a pull request too?
I tried to this but it seems I don't have permission for it (yet).

**Comment by liayn** [comment]
what is "origin"? your fork or this repository here?
This is my process to set up things:
* Fork the repo on github into your account
* Clone the original repo on your machine
* Add your repo as a second remote (name the remote as you like, I call it "my" usually)

To create a PR:
* `git checkout -b my-fix`
* ... coding ...
* `git commit -a -m "... the message"`
* `git push my`
* Go to the repository on github, a button should appear to create a PR.

**Comment by stefahn** [comment]
"origin" is my cloned remote on my HDD. So it should be the repository here.

I understand your workflow. So you push to **your** fork and do the pull request by a mouse click.

Is your workflow the common one? 
Would be easier if there's a way to do the pull request via command line...

**Comment by liayn** [comment]
I'm not aware of any other way how things should work with github.
https://help.github.com/articles/using-pull-requests/

IMHO the only real serious workflow would be to use Gerrit, but that's a different topic. I just dislike this horrible pull request stuff on github.

**Pull request merged**
