### PR TITLE
Fixes IE Bug when adding multiple classes to elements

### PR DESCRIPTION
**Pull request by BrunoFenzl**
IE's implementation of classList.add() does not accept multiple arguments, therefore we need to split the arguments and add them sequentially.

### CODE REVIEW

**Comment by BrunoFenzl** [comment]
This is a fix proposal for #255

**Comment by xi** [comment]
#255 is a pull-request, not an issue. So this is a duplicate (though it contains some other things).

**Comment by BrunoFenzl** [comment]
Hi @xi, sorry I was following the issue and thought 255 was its number.  Reference is fixed now.

**Comment by pmb0** [comment]
Hi @BrunoFenzl BrunoFenzl, thanks for your contribution. I didn't see this PR. The issue was fixed in https://github.com/heiseonline/shariff/commit/ae20a34c0281e82924241d5090904cad7e2d42ed.

**Pull request closed without merging**
